---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gpu-dev-server.controlplaneNamespace" . }}
  labels:
    {{- include "gpu-dev-server.labels" . | nindent 4 }}
    component: controlplane
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gpu-dev-server.workloadsNamespace" . }}
  labels:
    {{- include "gpu-dev-server.labels" . | nindent 4 }}
    component: workloads
