{{- if eq .Values.cloudProvider.name "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "gpu-dev-server.storageClass" . }}
  labels:
    {{- include "gpu-dev-server.labels" . | nindent 4 }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
{{- if eq .Values.cloudProvider.name "gcp" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "gpu-dev-server.storageClass" . }}
  labels:
    {{- include "gpu-dev-server.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
